### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by macumber** [bincrafters/community#681]
### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **boost_log/1.69.0** **boost_asio/1.69.0**
  * Operating System+version: **Windows 10**
  * Compiler+version: **Visual Studio 2017**
  * Conan version: **Conan 1.11.0**
  * Python version: **Python 3.7.0**

### Question Description

I am new to conan and it is going pretty well so far.  However, I am having trouble with boost asio.  I am trying to build with OpenSSL/1.1.0i and have listed this in my conan_cmake_run REQUIRES.  I am trying to coordinate OpenSSL versions across boost, cpprest, and a custom build of Ruby (not yet built with conan).  I am using boost log, which depends on boost asio, which appears to use a different version of OpenSSL.   This is resulting in errors like:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol CRYPTO_cleanup_all_ex_data referenced in function "private: virtual void __cdecl std::_Ref_count<class boost::asio::ssl::detail::openssl_init_base::do_init>::_Destroy(void)" (?_Destroy@?$_Ref_count@Vdo_init@openssl_init_base@detail@ssl@asio@boost@@@std@@EEAAXXZ)	openstudio_utilities_static_tests	D:\openstudio_refactor2\build-release\src\utilities\cpprest141_2_10.lib(http_client_winhttp.obj)	1	
```

I don't really need the ssl functions in boost asio.  Is there any advice on how to:

- build boost asio without ssl functions
- build boost asio against the version of OpenSSL I am using
- something else that I should be doing

**Comment by macumber** [comment]
OpenSSL is listed as an [optional dependency](https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio/using.html#boost_asio.using.dependencies) for boost.  I don't see any [relevant configuration variables](https://www.boost.org/doc/libs/1_69_0/doc/html/boost_asio/using.html) to turn off ssl support in boost asio.

**Comment by macumber** [comment]
Is it possible to define `BOOST_LOG_NO_ASIO` in the configuration of boost log?

**Comment by solvingj** [comment]
will look into tomorrow

**Comment by macumber** [comment]
Thanks, it seems that cpprest is using boost asio as well so I am going to try rebuilding our custom Ruby version as a first step.

**Comment by solvingj** [comment]
I am very surprised and troubled to see that our `boost_asio` package doesn't have OpenSSL as an optional dependency.  We need to add it.
