### ISSUE TITLE
conan-qt/5.15.0: new build issue since 28 Mai - flags changed?

### ISSUE THREAD

**Issue by EugenMayer** [bincrafters/community#1267]
I'am using my CI build without any changes, last successfull build was from May 28/2020 - the same QT version.
The git commithash from that working build was

```
current QT git revision is: 25e7cdbcf8759b2c837c85f5bf8d2c58aa9b900d
```
So https://github.com/bincrafters/conan-qt/commit/25e7cdbcf8759b2c837c85f5bf8d2c58aa9b900d

with those options
```
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=7
os=Linux
os_build=Linux
[options]
glib:shared=False
qca:shared=True
qt:opengl=no
qt:qttools=True
qt:shared=True
qt:with_fontconfig=True
qt:with_harfbuzz=False
qt:with_libalsa=False
qt:with_libjpeg=False
qt:with_libpng=True
qt:with_mysql=False
qt:with_odbc=False
qt:with_openal=False
qt:with_pcre2=True
qt:with_pq=False
qt:with_sdl2=False
qt:with_sqlite3=False
qt:with_zstd=False
[build_requires]
[env]
```

## Problem
Today i get this build error

```
ERROR: qt/5.15.0@kwconan/stable: Error in requirements() method, line 326
	if not tools.cross_building(self, skip_x64_x86=True):
	AttributeError: 'QtConan' object has no attribute 'get_safe'
```

Could that be related to the conan version /compatiblity?

```
conan --version
Conan version 1.21.1
```

Sidenote: i really LOVE https://github.com/bincrafters/conan-qt/blob/testing/5.15.0/CHANGELOG.md 
Thank you so much for doing this @ericLemanissier

**Comment by ericLemanissier** [comment]
It very much looks like your conan version is outdated for the qt recipe indeed. Bincrafters and Conan Center Index recipe often require an up-to-date version of conan, because a lot of the new features of conan arise from CCI recipes which cannot do their job because of a limitation in conan.
It's good to hear that this changelog is useful. Don't hesitate to give some momentum on https://github.com/conan-io/conan/issues/6771 (or another relavant issue)

**Comment by EugenMayer** [comment]
trying to gather some informations. Could that be somehow related?

https://github.com/bincrafters/conan-qt/commit/3f6d984b47a12f61840a676e46f02605cf435a56

I mean i'am not using 1.28 though - maybe that is the actual issue in the first place? Trying to build with 1.28.2 now.

**Comment by EugenMayer** [comment]
> It very much looks like your conan version is outdated for the qt recipe indeed. Bincrafters and Conan Center Index recipe often require an up-to-date version of conan, because a lot of the new features of conan arise from CCI recipes which cannot do their job because of a limitation in conan.
> It's good to hear that this changelog is useful. Don't hesitate to give some momentum on [conan-io/conan#6771](https://github.com/conan-io/conan/issues/6771) (or another relavant issue)

oh sorry - our comments overlapped. Ok so i guess the smell was right :) Jumping right on 1.28 then and making this a "todo check this first" thing for the next time, before asking anything here. Sorry! I will close the issue after testing 1.28

**Comment by EugenMayer** [comment]
The old/initial issue has been solved by upgrading conan, now i get

```
ERROR: The following packages need to be installed:
 xorg-dev
xorg/system: ERROR: while executing system_requirements(): Aborted due to CONAN_SYSREQUIRES_MODE=verify. Some system packages need to be installed
ERROR: Error in system requirements
```

which is expected due to https://github.com/bincrafters/conan-qt/commit/d504c309fe8a551b72a580157d5fe47915f8aa74 aka `linux: make xlib requirement shared by default - 2020-06-08`

AFAIR until then, x11lib / libxcb where shared, but now are expected to be compiled into the binary, right - that's why xorg-dev is needed. If i want to stay with the shared type, i add

```
libxcb:share=True
libx11:shared=True
```

to my options and should be back to the old variant. Beside that - are there any particular reasons you decided to compile them statically by default now? Are there any new guidelines or what is the reason?

**Comment by ericLemanissier** [comment]
the commit you linked just remove the dependancy on libxcband libx11 conan packages, and replaces it with xorg/system, which is just a proxy package for the system packages of xcb, x11 et al. you will solve this error by setting environment variable `CONAN_SYSREQUIRES_MODE=enabled` : https://docs.conan.io/en/latest/reference/env_vars.html#conan-sysrequires-mode, or manually install system package `xorg-dev`

**Comment by EugenMayer** [comment]
I guess i will then follow up with all this https://github.com/bincrafters/community/issues/1229 .. if i decide to pick the manual route, right

**Comment by EugenMayer** [comment]
Does this also mean, i no longer need `libx11-dev` and respectivly `libxcb-xkb-dev` ?

**Comment by ericLemanissier** [comment]
the error message will tell you what packages to install:
```
ERROR: The following packages need to be installed:
 xorg-dev
```
You can also get all the packages here: https://github.com/conan-io/conan-center-index/blob/master/recipes/xorg/all/conanfile.py#L41-L43

**Comment by EugenMayer** [comment]
So that was exactly what was missing. Summary for all the google-visitors:
 - upgrade conan to 1.28 ( 1.21 was no longer working with the current 5.15.0 qt reciepe )
 - add new/missing dependencies due to the `xorg/system` changes

Thank you (once again) @ericLemanissier !
