### ISSUE TITLE
[qt/5.13.2] Fails to build on Ubuntu 18.04 with Conan 1.21

### ISSUE THREAD

**Issue by Morwenn** [bincrafters/community#1063]
The `qt/5.13.2` recipe stopped compiling on Ubuntu 18.04 without specific changes to the way we use it. Here are select elements from the log that feel like they could be culprits (the full logs are at the end of the post):

```
Note: Disabling X11 Accessibility Bridge: D-Bus or AT-SPI is missing.
```

```
ERROR: Feature 'glib' was enabled, but the pre-condition 'libs.glib' failed.
```

```
> main.cpp:2:10: fatal error: EGL/fbdev_window.h: Aucun fichier ou dossier de ce type
>  #include <EGL/fbdev_window.h>
```

Looking at the recipe's changelog it seems that the way X11 and glib libraries are handled was changed recently in the recipe, so I wouldn't be surprised if my issue was linked to one of these changes.

### Package and Environment Details (include every applicable attribute)
  * Package Name/Version: **qt/5.13.2**
  * Operating System+version: **Linux Ubuntu 18.04**
  * Compiler+version: **gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0**
  * Conan version: **conan 1.21.0**
  * Python version: **Python 3.6.9**

### Conan profile (output of `conan profile show default` or `conan profile show <profile>` if custom profile is in use)

```
[settings]
os=Linux
os_build=Linux
arch=x86_64
arch_build=x86_64
compiler=gcc
compiler.version=7
compiler.libcxx=libstdc++11
build_type=Release
[options]
[build_requires]
[env]
```

### Steps to reproduce (Include if Applicable)

Quite complicated since our stack is becoming huge, Qt is used by several other libraries and everything worked until very recently. If I don't forget anything the Qt recipe is compiled with the following options (all the other options have their default values):

```
qt:commercial=False
qt:shared=True
qt:qtx11extras=True
qt:.with_mysql=False
```

Simply building the Qt recipe with those options 

EDIT: I confirm that I can reproduce the error with the following line alone:

```cpp
conan install qt/5.13.2@bincrafters/stable -o qt:shared=True -o qt:qtx11extras=True
```

### Logs (Include/Attach if Applicable)

The logs are unsurprisingly massive, so I had to upload them in a separate Gist because they're too long for GitHub issues: https://gist.github.com/Morwenn/20dbf59e61989f605fc40fee652b62d1

**Comment by ericLemanissier** [comment]
Thanks for this precise report.
You are right, the blocking error is `ERROR: Feature 'glib' was enabled, but the pre-condition 'libs.glib' failed.`
The relevant part of the log says 
```
looking for library glib
Trying source 0 (type pkgConfig) of library glib ...
+ /usr/bin/pkg-config --exists --silence-errors glib-2.0 gthread-2.0
pkg-config did not find package.
```
Can you try to update conan, and use the arguments `-u --build=outdated` of `conan install` to make sure everything is up to date ?
If it gives the same result, please check if the folder ` ~/.conan/data/qt/5.13.2/bincrafters/stable/build/49177b36708f0eb4abb154d3760d2125340f2fd3/` has files `glib-2.0.pc` and `gthread-2.0.pc`

**Comment by Morwenn** [comment]
Keeping track of our conversation in case somebody else drops by: the issue is caused by a mismatch between the file name `bzip2.pc` and a pkg-config requirement for `BZip2`. The root is the handling of names in recipes (`cpp_info.name`, `cpp_info.names`)  in Conan 1.21 and the existence of a special case for the `pkg_config` generator.

In the meantime the specific workaround for this recipe is to disable glib with `qt:with_glib=False` (or the pcre dependency of glib, or the bzip2 dependency of pcre).

The next step is conan-io/conan#6211.

**Comment by ericLemanissier** [comment]
I committed a workaround : https://github.com/bincrafters/conan-qt/commit/94f024fad2a6463715eef741c1d39d1e182d03ef
